stages:
  - build
  - test
  - deploy

variables :
  - CI_EXTERNAL_PULL_REQUEST_
  
trigger_pipeline:
  stage: deploy
  script:
    - 'curl --fail --request POST --form token=$MY_TRIGGER_TOKEN --form ref=main "https://gitlab.example.com/api/v4/projects/123456/trigger/pipeline"'
  rules:
    - if: $CI_COMMIT_TAG
  environment: main

build_job:
  stage : build
  script :
    - echo "Build done"

test_job:
  stage : test
  script :
    - echo "Done tests"

deploy_job:
  stage : deploy
  script : 
    - echo "Hello"
